spring:
  application:
    name: GestionUsuarios
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_usuarios
    username: postgres
    password: pruebas
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
jwt:
  secret-key: bXlfc3VwZXJfc2VjcmV0X2tleV9wYXJhX2p3dF9xdWVfZGViZV90ZW5lcl8yNTZiaXRz